name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install and patch gitbook
        run: |
          npm install -g gitbook-cli
          cd /usr/local/lib/node_modules/gitbook-cli/node_modules/npm/node_modules
          sed -i 's/fs.stat = statFix(fs.stat)/\/\/fs.stat = statFix(fs.stat)/' graceful-fs/polyfills.js
          sed -i 's/fs.fstat = statFix(fs.fstat)/\/\/fs.fstat = statFix(fs.fstat)/' graceful-fs/polyfills.js
          sed -i 's/fs.lstat = statFix(fs.lstat)/\/\/fs.lstat = statFix(fs.lstat)/' graceful-fs/polyfills.js
          cd -
          gitbook install

      - name: Build documentation
        run: |
          gitbook build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          force_orphan: true