name: Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm init -y
          npm install honkit --save-dev
          npm install web-streams-polyfill --save-dev
          npm install

      - name: Build documentation
        run: |
          node -e "global.ReadableStream = require('web-streams-polyfill').ReadableStream" -e "require('honkit').build()"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_book
          force_orphan: true